FROM pycbc/pycbc-el8:latest

# Installer les dépendances globales nécessaires
RUN pip install --no-cache-dir ipykernel matplotlib numpy scipy pandas 
    gwmemory gwsurrogate
ENV GWSURROGATE_DIR=/home/pycbc/gwsurrogate_downloads


